#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

# source files in this project (main.cpp is automatically assumed)
SOURCES := drawable.cpp picture.cpp gameControl.cpp action.cpp dirt.cpp vehicle.cpp tractor.cpp

# header files in this project
HEADERS := drawable.hpp picture.hpp gameControl.hpp action.hpp dirt.hpp vehicle.hpp tractor.hpp

# other places to look for files for this project
SEARCH  := 

# set REATIVE to the next higher directory 
# and defer to the Makefile.due there
RELATIVE := $(RELATIVE)../
include $(RELATIVE)Makefile.native
