#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

# source files in this project (main.cpp is automatically assumed)
SOURCES += drawable.cpp
        SOURCES += picture.cpp
        SOURCES += gameControl.cpp
        SOURCES += action.cpp
        SOURCES += dirt.cpp
        SOURCES += vehicle.cpp
        SOURCES += tractor.cpp
        SOURCES += rectangle.cpp
        SOURCES += menu.cpp
        SOURCES += farmhouse.cpp
        SOURCES += harvester.cpp
        SOURCES += particleSystem.cpp
        SOURCES += pauseMenu.cpp
        SOURCES += option.cpp
        SOURCES += player.cpp
        SOURCES += saver.cpp
        SOURCES += loader.cpp
        SOURCES += inventory.cpp


# header files in this project
HEADERS += drawable.hpp
        HEADERS += picture.hpp
        HEADERS += gameControl.hpp
        HEADERS += action.hpp
        HEADERS += dirt.hpp
        HEADERS += vehicle.hpp
        HEADERS += tractor.hpp
        HEADERS += rectangle.hpp
        HEADERS += menu.hpp
        HEADERS += farmhouse.hpp
        HEADERS += harvester.hpp
        HEADERS += particleSystem.hpp
        HEADERS += pauseMenu.hpp
        HEADERS += option.hpp
        HEADERS += player.hpp
        HEADERS += saver.hpp
        HEADERS += base64.hpp
        HEADERS += loader.hpp

        HEADERS += inventory.hpp


# other places to look for files for this project
SEARCH  :=

# set REATIVE to the next higher directory
# and defer to the Makefile.due there
RELATIVE := $(RELATIVE)../
include $(RELATIVE)Makefile.native