#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

# source files in this project (main.cpp is automatically assumed)
SOURCES += drawable.cpp
SOURCES += picture.cpp
SOURCES += gameControl.cpp
SOURCES += action.cpp
SOURCES += dirt.cpp
SOURCES += vehicle.cpp
SOURCES += tractor.cpp
SOURCES += rectangle.cpp
SOURCES += menu.cpp
SOURCES += pauseMenu.cpp
SOURCES += option.cpp
SOURCES += farmhouse.cpp

# header files in this project
HEADERS += drawable.hpp
HEADERS += picture.hpp
HEADERS += gameControl.hpp
HEADERS += action.hpp
HEADERS += dirt.hpp
HEADERS += vehicle.hpp
HEADERS += tractor.hpp
HEADERS += rectangle.hpp
HEADERS += menu.hpp
HEADERS += pauseMenu.Hpp
HEADERS += option.hpp
HEADERS += farmhouse.hpp

# other places to look for files for this project
SEARCH  := 

# set REATIVE to the next higher directory 
# and defer to the Makefile.due there
RELATIVE := $(RELATIVE)../
include $(RELATIVE)Makefile.native
